<?php
/**
 * @author - Jhalak
 */

function entityfieldquery_menu(){
  return array(
    'sessions' => array(
      'title' => t('Sessions'),
      'page callback' => 'entityfieldquery_list',
      'access arguments' => array('access content'),
    )
  );
}

function entityfieldquery_list(){
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', array('session'))
    ->fieldCondition('field_speaker', 'value', 'Jhalak', '=');
  $result = $query->execute();
  if (empty($result['node'])) {
    return t('No entry found.');
  }
  $nodes = array_keys($result['node']);
  return node_view_multiple(node_load_multiple($nodes));
}

function entityfieldquery_list_with_db_select(){
  $query = db_select('node', 'n');
  $query->fields('n', array('nid'));
  $query->join('field_data_field_speaker', 's', 's.entity_id = n.nid');
  $query->condition('type', 'session', '=');
  $query->condition('s.field_speaker_value', 'Jhalak', '=');
  $result = $query->execute();

  if ($result->rowCount() <= 0) {
    return t('No entry found.');
  }
  $nodes = array();
  while($record = $result->fetchAssoc()) {
    $nodes[] = $record['nid'];
  }
  return node_view_multiple(node_load_multiple($nodes));
}

function dump($var){
  echo '<pre>';
  print_r($var);
  exit;
}